# Uncomment the next line to define a global platform for your project
#platform :ios, ’10.0’

target 'awesomeApp3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for awesomeApp3
  pod 'SCLAlertView-Objective-C'

  target 'awesomeApp3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'awesomeApp3Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

